// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2zEx3dna8XiP84qS30I8rtHEPXwtw8Zg',
    appId: '1:217547396506:web:d9a3de01651ef7c8605623',
    messagingSenderId: '217547396506',
    projectId: 'flutter-demo-c8676',
    authDomain: 'flutter-demo-c8676.firebaseapp.com',
    storageBucket: 'flutter-demo-c8676.appspot.com',
    measurementId: 'G-NLQ1FKS8HC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmNeR4RLYjnPb0HaHe0aIgL5qHdbennCU',
    appId: '1:217547396506:android:f11d6e74d28d1f9c605623',
    messagingSenderId: '217547396506',
    projectId: 'flutter-demo-c8676',
    storageBucket: 'flutter-demo-c8676.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9hjjLWh-vwf-MMecpcNH5PyfmsEp5Mro',
    appId: '1:217547396506:ios:9e68147d451f6b1b605623',
    messagingSenderId: '217547396506',
    projectId: 'flutter-demo-c8676',
    storageBucket: 'flutter-demo-c8676.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9hjjLWh-vwf-MMecpcNH5PyfmsEp5Mro',
    appId: '1:217547396506:ios:9dcecbd671d04738605623',
    messagingSenderId: '217547396506',
    projectId: 'flutter-demo-c8676',
    storageBucket: 'flutter-demo-c8676.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
